platform :ios, '12.0'

use_frameworks!

target 'Example' do

  pod 'LifetimeTracker', :path => '../'
  pod 'LifetimeTrackerCore', :path => '../'

  target 'Example_Tests' do
    inherit! :search_paths
  end

end
